# Generated by Django 5.2.2 on 2025-06-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_forumthread_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecomment",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
