# Generated by Django 5.1.6 on 2025-08-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_article_slug_alter_articlecomment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='event_pdfs/'),
        ),
    ]
