# Generated by Django 5.1.3 on 2025-08-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_articlecomment_is_approved"),
        ("app", "0004_event_pdf_file"),
    ]

    operations = []
